TOP = ..

USER_LIBS = -nodefaultlibs -lc -lgcc

TARGET = midilights

CPPSRC = main.cpp \
         timer.cpp \
         isr.cpp \
         led.cpp \
         midi.cpp \
         color.cpp \
         lcd.cpp \
         key.cpp \
         uart.cpp

include $(TOP)/mk/common.mk
